#!/bin/bash

JAVA=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home/bin/java
CLJ_DIR=$HOME/dev/lang/clojure-1.5.1/lib/
CLOJURE=$CLJ_DIR/clojure-1.5.1.jar
JLINE=$CLJ_DIR/jline-1.0.jar
CP=$PWD:$CLOJURE:$JLINE

# Add extra jars as specified by `.clojure` file
if [ -f .clojure ]
then
CP=$CP:`cat .clojure`
fi

if [ -z "$1" ]; then
$JAVA -server -cp $CP \
jline.ConsoleRunner clojure.lang.Repl
else
scriptname=$1
$JAVA -server -cp $CP clojure.lang.Script $scriptname -- $*
fi

